title = "standard3"
languageCode = "en-us"
baseurl = "https://blog.theoabel.com"
paginate = 20
canonifyurls = true

[module]
  [[module.imports]]
    path = "hugo-xterm"

[params]
  centerTheme = true
  showMenuItems = true
  favicon = "/images/favicon.ico"
  showBreadCrumbs = true
  toc = true
  copyrightUserUrl = "https://blog.theoabel.com"
  copyrightUserText = ""
  author = "Théo Abel"

[params.site_verification]
  google = "dRxlQUCTcreupAiAU9R-WcImzIL5ZkXVFT4PVPDJl6Y"
  bing = "F82FFC97299503C8B6340178FE5F1EFA"
  yandex = "146d77656fc95385"
  naver = "e3b93136c43487a12e31584cf30306a269137968"

[languages]
  [languages.en.params]
    copyright = "© Théo Abel"
    readOtherPosts = "Lire d'autres publications"
    missingContentMessage = "La page n'existe pas 💀"
    missingBackButtonLabel = "Retour à l'accueil"

    [languages.en.params.logo]
      logoText = "Home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Publications"
        url = "/posts/"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "À propos"
        url = "/about/"
        
      [[languages.en.menu.main]]
        identifier = "docs"
        name = "Documents"
        url = "/docs/"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
